### ISSUE TITLE
Error: Line number (45) greater than maximum line (44)

### ISSUE THREAD

**Issue by florianb** [AtomLinter/linter-pylint#147]
When working on a python-file this ominous error occurred. I am currently not sure what exactly is the problem.

```
Error: Line number (45) greater than maximum line (44)
    at Object.rangeFromLineNumber (/Users/florianbreisch/.atom/packages/linter-pylint/node_modules/atom-linter/lib/helpers.js:141:11)
    at /Users/florianbreisch/.atom/packages/linter-pylint/lib/main.coffee:106:36
    at Array.map (native)
    at /Users/florianbreisch/.atom/packages/linter-pylint/lib/main.coffee:102:16
    at process._tickCallback (node.js:392:9)
```

![image](https://cloud.githubusercontent.com/assets/983507/15218465/5b08042e-1860-11e6-8baf-6f66101e3342.png)

### Additional Information:

```
Community Packages (29) /Users/florianbreisch/.atom/packages
├── aligner@0.22.0
├── atom-bootstrap3@1.2.12
├── atom-terminal@0.8.0
├── autocomplete-clang@0.9.3
├── build@0.62.0
├── editorconfig@1.4.1
├── git-time-machine@1.5.2
├── hex@0.6.2
├── language-antlr@0.1.0
├── language-ini@1.16.0
├── language-latex@0.6.1
├── language-nginx@0.6.1
├── language-pegjs@0.5.0
├── language-salt@0.4.0
├── linter@1.11.4
├── linter-coffeelint@1.1.2
├── linter-gcc@0.6.14
├── linter-javac@1.9.1
├── linter-jsonlint@1.2.5
├── linter-pylint@1.2.0
├── linter-xo@0.15.0
├── merge-conflicts@1.4.2
├── npm-install@4.0.3
├── platformio-ide@1.2.1
├── platformio-ide-terminal@2.0.9
├── react@0.15.0
├── riot@0.4.1
├── tool-bar@0.4.0
└── travis-ci-status@1.0.0
```

```
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.4
```

**Comment by Arcanemagus** [comment]
Are you able to share the file? Does `flake8` from the command line show the invalid error range? Since it's only off by one does it appear/disappear if you change the line endings of the file?

**Comment by florianb** [comment]
I couldn't reproduce this yet and the current file is (and was) absolutely valid.

💭 I have the impression it happened at saving the file (which is something i'm doing unconsciously) and may be caused by the run of the whitespace package (which strips off last lines).

Could it be, that the file might change due to such events (loosing lines at the end?) before the errors are shown by the linter?

P.s.: I thought this package would only use the pylint -- and of course its output is perfectly reasonable.

**Comment by Arcanemagus** [comment]
Oh wow, thought this was filed on `linter-flake8` :stuck_out_tongue:.

That actually is quite the possibility: The lint is triggered on the fly, sends off the current text to `pylint`, it takes long enough to return that the file has been modified since then to change, and when `rangeFromLineNumber` tries to validate the point it is no longer valid.

For now I'm going to mark this as closed under the assumption that the above is happening. If you can find a file that reproduces this every time please re-file the issue. Thanks for pointing out that possible scenario for that to happen, I don't really think there is anything that can be done to prevent it though :confused:.

**Comment by florianb** [comment]
I think this can't be solved, too. 💭 But if you know where this happens, the code could probable made more robust, turning the exception into a log-entry?

**Comment by Arcanemagus** [comment]
The part that is throwing the error doesn't know what is going on, all it knows is what called it gave it an invalid range, so it reports that back. I would probably recommend just bumping up your on the fly lint delay in `linter`, I personally use 1500 ms.

**Comment by florianb** [comment]
I see - it would probably be worth ignoring or dropping the message instead of raising an error? I mean as long as the reason is known as unfixable the code should in my opinion not throw an error indicating that something went's wrong.

Good Point - i guess i'll raise it to 600ms. Well, the error only happened once, so i don't expect to see it that often.

**Comment by Arcanemagus** [comment]
How would you recommend we detect that the mistaken range was due to a change in the editor, instead of a broken linter? If you have a good way of detecting that that would be awesome!

**Comment by florianb** [comment]
Hmm - that may be the problem. I don't know if you have access to the current TextEditor, if so i believe it would be the fastest thing to compare the line numbers to `TextEditor.getBufer().getLineCount()`.

**Comment by Arcanemagus** [comment]
That wouldn't have helped here, where it was just whitespace being removed from a line though.

**Comment by florianb** [comment]
I think some empty lines were removed at that point and i thought that's what the error states, that the buffer misses the line corresponding to the linter-message?

**Comment by Arcanemagus** [comment]
Ah, yea, was thinking it was column count above. Still how to tell whether the bad line is due to modification of the buffer after the call, or just bad data from the linter?

**Comment by florianb** [comment]
In this context i guess it's a wrong information from the linter -- which is, because of the way how the API is designed, not the fault of the pylint. Probably the helpers should drop invalid messages or try/without catch placing the linter-message.

**Comment by Arcanemagus** [comment]
I've thought about putting it in a try/catch before, and only reporting if the user is in dev mode... but then we would never get any reports of bugs in the linters themselves since almost nobody runs Atom in dev mode normally.

Having seen many bugs in linters fixed due to it I personally think it's better to leave it in and get the errors fixed for _everyone_ using the linter, but package authors are free to suppress it if they want.

**Comment by florianb** [comment]
I see the point... The only way i see how this may be solved without dropping invalid messages (and i thought of the same drawback, too) would be to ensure that the current lint is immediately dropped and restarted if the buffer/editor changed until the result has been displayed.

**Comment by marksherman** [comment]
Hello, and welcome back to this long-closed thread! I'm seeing this bug rear its head again. 

This bug is happening in many other atom linter packages. I'm currently using pylint, so I decided to talk about it here. 

Right now It's happening every few minutes, but not _every time,__ so I can't call it easily-reproducible either. But I made a video, below.

@Arcanemagus, I see you tend to present in all the discussions about this bug, across many different linters. I think the hypothesis in this thread, about the timeout, might have some meat to it. (Is this the grand-father thread? https://github.com/steelbrain/atom-linter/issues/63)

Today, the bug triggers when:
- adding a new line which auto-indents (where column start and line length are both numbers)
- deleting an empty line (where column start is a number and line length is reported 0)

The file has consistent indentation throughout (though a path over a year ago should make that not matter). 

Interestingly, the linter does continue to function normally, despite the error appearing. I show that in the video.

I made a screen recording of me fiddling around trying to exercise the bug. The video is here:
https://youtu.be/RAXvW8jaUKo

Here's the file I was playing with: https://gist.github.com/marksherman/43519cd53be522e85e694925683965d6

This project doesn't have a package.json- it's brand-new and is just that one file. 
linter-pylint is installed in atom using default configuration. 
Here's what's installed in atom:
```
$ apm list --installed
Community Packages (21) /Users/mark/.atom/packages
├── atom-bootstrap3@1.2.12
├── autoclose-html@0.23.0
├── jslint@1.5.1
├── linter@1.11.14
├── linter-bootlint@1.0.2
├── linter-csslint@1.3.2
├── linter-eslint@7.2.4
├── linter-htmlhint@1.2.1
├── linter-jshint@2.1.0
├── linter-pylint@1.2.1
├── merge-conflicts@1.4.4
├── minimap@4.24.7
├── minimap-bookmarks@0.3.1
├── minimap-color-highlight@4.1.4
├── minimap-find-and-replace@4.5.1
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.4.0
├── minimap-pigments@0.2.1
├── minimap-selection@4.4.0
├── pigments@0.31.1
└── tab-control@0.6.9
```

Thanks for all your help, @Arcanemagus, I see you've dealt with this one quite a bit.

**Comment by eMerzh** [comment]
Yeah i experience it everyday. might be related to the way i work (many hit ctrl+s) while still editing, but it's really anoying.... it should at least fail in silence :)

**Comment by leonexis** [comment]
I'm experiencing this every few minutes while writing python. It is not tied to when I save. It breaks development flow. As with @marksherman, it appears to occur most often when pressing enter to start a new line that auto-indents. Also, increasing the linter delay seems to reduce the occurrences, but doesn't remove them completely (I have mine set to 1500ms).

Is there any way to cancel sending the pylint data to atom-linter if the buffer was modified while pylint was running? This might ensure there isn't a mismatch in line/col numbering. Since keystrokes would probably be required for the change in the buffer to occur, another invocation of pylint may already be scheduled to check the new buffer contents so canceling the previous one might not be so bad. If not, linter-pylint could re-invoke pylint instead. Might be a crazy idea and I'm not sure what bugs modifying this behaviour might cause.

**Comment by Arcanemagus** [comment]
This thread is the one where the root of issues like what you are showing seems to have really been found (editor contents changed after the lint run is started).

You can minimize your chances of seeing that by either disabling lint-on-fly in `linter`'s settings (turning _all_ linters in "lint-on-save", or you can increase the delay between when you stop changing the file and a lint being triggered. Neither of those are going to prevent the issue though, since the problem is that the results being returned aren't actually for what you have in your editor any longer.

As for how that can be _solved_, I honestly have no idea. You can do horrible annoying things like preventing all modifications to the editor while a lint is running (I'm sure users will just _love_ that 😛). <emory/time intensive things like creating a shadow TextEditor at the time of a lint call, running against that, then only keeping messages that are valid ranges for the current TextEditor would also "work", but sound like they would absolutely destroy performance.

Possibly the best option I can think of is to make any buffer modification kill the process of and ignore any pending lint requests. This would cause a _lot_ of "churn" for linters that are generating temporary files to lint against though, and may lead to issues with cleanup.

Does anyone have a better idea?
