### ISSUE TITLE
Lint also Django Python files

### ISSUE THREAD

**Issue by michel-m** [AtomLinter/linter-pylint#17]
It would be great to have pylint working in Python Django files too. (Syntax from packages such as atom-django by @zacharytamas.)

**Comment by exploide** [comment]
Don't know what advantages an integration with atom-django (or similar packages) would have.

But installing the pylint-django plugin for pylint improves the Django support of atom and linter-pylint significantly.

https://github.com/landscapeio/pylint-django

**Comment by yoongkang** [comment]
@exploide, I'm having a bit of trouble getting pylint-django to work with linter-pylint.

Under the executables setting, I added "pylint --load-plugins pylint_django" but it crashes pylint. I can run the command from cli with no issue. Any tips?

**Comment by exploide** [comment]
* Make sure pylint is installed for the version of Python you are using (2 vs 3)
* Make sure pylint-django is installed for the version of Python you are using (pip2 vs pip3 if you install it via pip)
* To load the plugin, I placed the following `.pylintrc` file in my home directory:
```
[MASTER]

# List of plugins (as comma separated values of python modules names) to load,
# usually to register additional checkers.
load-plugins=pylint_django
```
This avoids the command line switch mentioned in your comment.
* If it still does not work, try to run pylint directly from terminal instead of using the Atom package. This should help to nail the problem down and see verbose output.

**Comment by SpainTrain** [comment]
@yoongkang did explode's fix work for you?

Closing as this is an old issue and the ` pylint-django` solution seems reasonable.  If there are still Django integration issues, please open an issue.

**Comment by exploide** [comment]
Well, the use of pylint-django is okayish. In general it works but I always got import errors like `F0401 Unable to import 'myapp.models'`. Don't know if this is a linter-pylint or pylint or pylint-django issue.

**Comment by SpainTrain** [comment]
> I always got import errors

Have you tried with the latest version of linter-pylint?  We fixed some import issues, so this may work for you now.  `pylint` itself does indeed have issues with some C modules and modules that dynamically export members, though.  If after upgrading you are still having issues, please open a new issue and we'll get it figured out!

**Comment by dccarmo** [comment]
I'm having the same issue as @yoongkang. Here's my `.pylintrc`:

```
# List of plugins (as comma separated values of python modules names) to load,
# usually to register additional checkers.
load-plugins=pylint_django
```

And Pylint/Python version:

```
pylint --version
pylint 1.7.1,
astroid 1.5.2
Python 3.6.1 (default, Apr  4 2017, 09:40:21)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

Using `linter-pylint` version `2.1.0`. 

And also if I run the command from cli it works (having the plugin loaded on `.pylintrc`)

**Comment by ddaanet** [comment]
@dccarmo Do you mean you added options to the executable path setting? If that's the case, a crash is normal, because this is no longer the correct executable path.

But it should not be needed, since you already configure `load-plugins` correctly in your `pylintrc`. The problem is probably that pylint does not find your pylintrc. Try setting the pylintrc file name explicitly.

By the way, reopening a years-old, closed bug, saying that you have the "same problem" is bad form. You are not describing your problem fully and it confuses the conversation.

**Comment by dccarmo** [comment]
@ddaanet Sorry if I wasn't clear enough.

I'm adding `pylint_django` to my `.pylintrc` `load-plugins` section. When I do that, `linter-pylint` crashes upon running. This is my issue.

Now if I try running `pylint` on the terminal, it runs without any issue, even loading the plugin from `.pylintrc`. So my guess is there's some issue on `linter-pylint` that's crashing when loading this plugin.

**Comment by ddaanet** [comment]
If `linter-pylint` crashes, it gives some output in the development console. Can you paste it here?

**Comment by ddaanet** [comment]
Or even better, in a new issue, because, you know, this one is closed...
