### ISSUE TITLE
Pylama not working 

### ISSUE THREAD

**Issue by MrExclusive** [AtomLinter/linter-pylint#218]
Pylama is not detecting errors when made, executable path to the pylama.exe C:\Python\Scripts\pylama.exe
Been having trouble trying to get this thing to work for ages. Any help is appreciated,

**Comment by ddaanet** [comment]
@MrExclusive This is the issue tracker for `linter-pylint`, the packages that handles direct integration with `pylint`. For issues regarding `pylama` support, please use the [`linter-pylama` issue tracker](https://github.com/AtomLinter/linter-pylama/issues).

Closing this issue as invalid, since it was filed in the wrong issue tracker.
