### ISSUE TITLE
Linting as you type no longer occurs

### ISSUE THREAD

**Issue by JiDoan** [AtomLinter/linter-pylint#232]
Pylint no longer lints on the fly as it used to.

Steps to reproduce:
1. Make changes in code
1. Don't save

Expected results:
* Linting occurs

Actual results:
* Linting does not occur until you save the file

Installation details:
* Atom 1.21.1
* `linter-pylint` 2.1.0
* `linter` 2.2.0

**Comment by ddaanet** [comment]
I do not know if this is intentional, but I do not think we should support _Lint on Change_ for pylint.

* In non-trivial code, pylint is slow, several seconds. That makes it impractical for _Lint on Change_.
* pylint works on modules within their package, in particular it resolves imports and does cross-module static analysis
  - so running pylint on an isolated temporary file will produce different results, and probably some unwanted errors.
  - fixing that would be rather tricky 
* I believe pylama supports _Lint on Change_ for pylint. So you could check it out.

**Comment by Arcanemagus** [comment]
This is the expected behavior:
https://github.com/AtomLinter/linter-pylint/blob/29cfdb35aba3558a24f24f853b228145828f5c8e/lib/main.js#L107

The previous behavior of copying the file contents to a temporary file and then linting that caused far more issues than it was worth, and was removed in https://github.com/AtomLinter/linter-pylint/pull/205.

**Comment by JiDoan** [comment]
Thanks for the suggestions, I think `pylama` fits the bill!
